language: node_js
node_js:
- 7.5
before_install:
- npm install -g snazzy
before_script:
- make semistandard
after_success:
- cat ./coverage-lcov/lcov.info | node_modules/coveralls/bin/coveralls.js
script:
- make test
